services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3145
      - DB_PATH=../Banco de dados Aqui/erp.sqlite
      - NEXT_PUBLIC_API_URL=http://localhost:3145/api
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3145:3145"
    volumes:
      - "../Banco de dados Aqui:/data:rw"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3145/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "
        echo 'Iniciando aplicação ERP-BR...'
        echo 'Verificando permissões do banco de dados...'
        chmod -R 777 /data /app/data 2>/dev/null || true
        echo 'Executando servidor...'
        node server.js
      "
